// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Helloworldex2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void helloworldex2() {
    driver.get("https://ansymore.uantwerpen.be/");
    driver.manage().window().setSize(new Dimension(1042, 697));
    {
      WebDriverWait wait = new WebDriverWait(driver, 300);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("container")));
    }
    driver.findElement(By.linkText("Courses")).click();
    driver.findElement(By.cssSelector(".views-row-7 h2")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Software Testing"));
    assertThat(driver.findElement(By.cssSelector(".field-professor-linked")).getText(), is("Professor: Serge Demeyer"));
    assertThat(driver.findElement(By.cssSelector(".field-assistants-linked > div")).getText(), is("Assistants: Mutlu Beyazıt, Onur Kilincceker"));
  }
}
