// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Helloworldex3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void helloworldex3() {
    vars.put("indexes", js.executeScript("var indexes = [1,2,3,4,5,6,7]; return indexes;"));
    ArrayList collectionIndexes = (ArrayList) vars.get("indexes");
    for (int iIndex = 0; i < collectionIndexes.size() - 1; iIndex++) {
      vars.put("index", collectionIndexes.get(i));
      driver.get("https://ansymore.uantwerpen.be/");
      driver.manage().window().setSize(new Dimension(1042, 697));
      {
        WebDriverWait wait = new WebDriverWait(driver, 300);
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("container")));
      }
      driver.findElement(By.linkText("Courses")).click();
      {
        WebDriverWait wait = new WebDriverWait(driver, 300);
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("container")));
      }
      vars.put("command", js.executeScript("return \"//div[\"+ arguments[0] + \"]/div/span/a/h2\"", vars.get("index")));
      driver.findElement(By.xpath("vars.get("command").toString()")).click();
      {
        WebDriverWait wait = new WebDriverWait(driver, 300);
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("container")));
      }
      {
        List<WebElement> elements = driver.findElements(By.id("container"));
        assert(elements.size() > 0);
      }
      {
        List<WebElement> elements = driver.findElements(By.cssSelector(".field > a"));
        assert(elements.size() > 0);
      }
    }
  }
}
